# Generated by Django 4.1.4 on 2022-12-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stockinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tradecode', models.CharField(max_length=100)),
                ('high', models.DecimalField(decimal_places=1, max_digits=2)),
                ('low', models.DecimalField(decimal_places=1, max_digits=2)),
                ('open', models.DecimalField(decimal_places=1, max_digits=2)),
                ('close', models.DecimalField(decimal_places=1, max_digits=2)),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
