# Generated by Django 4.1.4 on 2022-12-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_stockinfo_close_alter_stockinfo_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='close',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='high',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='low',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='open',
            field=models.FloatField(),
        ),
    ]
