# Generated by Django 4.1.4 on 2022-12-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_stockinfo_close_alter_stockinfo_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='tradecode',
            field=models.CharField(max_length=200),
        ),
    ]
